### PR TITLE
#95 Add support for proxy

### LINKED ISSUE #95: Option to specify proxies
**Describe the bug**
I can't find a way to define proxy information, e.g. in requests we can say `requests.get('http://example.org', proxies=proxies)`

**To Reproduce**
Steps to reproduce the behavior: NA

**Expected behavior**
There should be an option to pass proxy information.

**What actually happened**
NA

**Screenshots**
NA

**Environment:**
 - OS: Any
 - Python version 3.7.5
 - `apiron` version 5.0.0

**Additional context**
I'm happy to contribute if you could walk me through the project.

### PR DESCRIPTION
**Pull request by chankeypathak**
**This change is a:** (check at least one)
- [ ] Bugfix
- [x] Feature addition
- [ ] Code style update
- [ ] Refactor
- [ ] Release activity

**Is this a breaking change?** (check one)
- [ ] Yes
- [x] No

**Is the:**
- [x] Title of this pull request clear, concise, and indicative of the issue number it addresses, if any?
- [x] Test suite passing?
- [x] Code coverage maximal?
- [x] Changelog up to date?

**What does this change address?**
Resolves #95

**How does this change work?**
By passing proxies argument to underlying requests' methods

### CODE REVIEW

**Comment by daneah** [comment]
@chankeypathak it seems you'll need to thread `proxies` through a few other places in `client.py` to get things working—`call` is the top-level entrypoint to start with.

**Comment by chankeypathak** [comment]
@daneah Okay that didn't help. It's because `requests.Request` method doesn't support `proxies` argument. Could you suggest how can this be fixed?

**Comment by daneah** [comment]
@chankeypathak Sorry about that, bad assumption on my end! In that case, passing it to the session as you originally suggested is probably what's needed here.

**Comment by chankeypathak** [comment]
@daneah Okay. For my use case I've added below piece of code in https://github.com/ithaka/apiron/blob/dev/src/apiron/client.py#L243

```python
sessions.proxies.update({
    "http": "...",
    "https": "...",
})
```

It works for me but I'm wondering how can I incorporate that in your repo. If I add the argument in `call` method, then it'll have to be added in `Endpoint` class also. Because that's the only place from where `call` gets called. And users will have to specify the proxy variable for each endpoint, which doesn't look good. 

Can it be incorporated in `Service` class instead? So that for one service user has to provide the proxy information only once, not for each and every endpoint of that service?

**Comment by daneah** [comment]
@chankeypathak The [requests documentation](https://2.python-requests.org/en/master/user/advanced/#prepared-requests) shows an example that passes `proxies` to `requests.Session.send`, which we use [here](https://github.com/ithaka/apiron/blob/dev/src/apiron/client.py#L244-L249).

By passing an optional `proxies` keyword argument to `call`, and passing that to `send`, it should get things working. The use of `call` in `Endpoint` shouldn't need to be updated—note that it creates a `partial` that will accept the rest of the `call` arguments as defined in `client.py`.

To define proxies that will be in effect for any call to a particular service, I'll need to think through things a bit more! If you need a workaround in the meantime, the [environment variable approach](https://2.python-requests.org/en/master/user/advanced/#proxies) may get you some of what you need.

**Comment by chankeypathak** [comment]
@daneah Yes I'm good for now. Let me know when you decide on the design to support proxies.

**Comment by daneah** [comment]
@chankeypathak I tried this out this evening. The approach I took was to add `proxies = {}` to `ServiceBase` as a default value, and pass `proxies=service.proxies` in the call to `send` in `client.py`. If you'd like to make that change as well as update the assertions for calls to `send` in `tests/test_client.py`, I think that would be a change we can move forward with.

**Comment by chankeypathak** [comment]
@daneah Excellent. That looks good. However, the test case is failing with below exception. How do I mock `proxies`?

```bash
Expected: send(<Mock name='build_request_object()' id='139678653489216'>, timeout=(<MagicMock name='Timeout.connection_timeout' id='139678653490512'>, <MagicMock name='Timeout.read_timeout' id='139678653518944'>), stream=True, allow_redirects=True, proxies={})
Actual:   send(<Mock name='build_request_object()' id='139678653489216'>, timeout=(<MagicMock name='Timeout.connection_timeout' id='139678653490512'>, <MagicMock name='Timeout.read_timeout' id='139678653518944'>), stream=True, allow_redirects=True, proxies=<Mock name='mock.proxies' id='139678653510416'>) 
```

**Comment by daneah** [comment]
@chankeypathak Because `service` is mocked in those tests, what gets passed to the `send` call is the mock object's `proxies` attribute. You can update each asserted call to `proxies=service.proxies` in that test case, which will ensure the service's proxies value is indeed being used.

**Comment by chankeypathak** [comment]
@daneah That was it. I updated the test cases and can see that the build is successful.

**Comment by daneah** [comment]
@chankeypathak Awesome! Per [this comment](https://github.com/ithaka/apiron/issues/96#issuecomment-636339566) I think we need one more change to avoid breaking behavior for people passing in their own session objects:

```diff
- proxies=service.proxies,
+ proxies=session.proxies or service.proxies,
```

This will break the tests again—they could use some updating to make testing this situation easier, but for the moment you'll want to add `mock_session.proxies = {}` [here](https://github.com/ithaka/apiron/blob/dev/tests/test_client.py#L130).

**Comment by chankeypathak** [comment]
Good catch! I made the suggested change.

**Review by daneah — APPROVED** [review]

**Comment by daneah** [comment]
@chankeypathak Thanks for the discussion and work on this, I'll try to get one more pair of eyes on this and then get it merged!

**Review by michael-iden — APPROVED** [review]
Looks good. ✅

**Review by Niznikr — APPROVED** [review]

**Pull request merged**
